[build]
  # Since this is a Node.js API, we don't need to build anything
  # The build command just echoes a message
  command = "npm run build"
  
  # Publish directory - Netlify expects a static site, but we're deploying an API
  # We'll use a simple index.html that explains this is an API
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Functions configuration for serverless deployment
[functions]
  directory = "netlify/functions"

# Redirects for API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Fallback for SPA routing (if you add a frontend later)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CORS headers for API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"